# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

##############
# Appearance #
##############

# Choice of color theme
theme: Earth
# Automatically change light/dark mode based on user's preference?
day_night: true
# Choice of font
font: Native
# Choice of font size
font_size: m

####################################
# Search Engein Optimization (SEO) #
####################################

site_type: Person
local_business_type: ''
org_name: ''
description: 'A personal blogging site and project portfolio by Ken Yang Wu'

###########
# Contact #
###########

email: yangwu2020-at-gmail-dot-com
phone: 
address:
  street: 503 lake Dr
  city: Princeton
  region: NJ
  postcode: '08540'
  country: United States
  country_code: US
coordinates:
  latitude: ''
  longitude: ''
directions: ''
office_hours: ''
appointment_url: ''
contact_links: 
  - icon: 
    icon_pack: 
    name: 
    link: 
  - icon: 
    icon_pack: 
    name: 
    link: 
  - icon: 
    icon_pack: 
    name: 
    link: 
  - icon: 
    icon_pack: 
    name: 
    link: 

###############
# Site header #
###############

main_menu:
  # Display the navigation bar?
  enable: true
  # Align menu links: left (l), center (c), or right (r)
  align: l
  # Display your site title or `assets/media/logo*` image in the nav bar?
  show_logo: true
  # Show a language chooser (if you have translated your site content)?
  show_translations: true
  # If `show_translations` is enabled, do you wish to display the current language name?
  show_language: false
  # Let the user override the default light/dark mode of your theme?
  show_day_night: true
  # Let the user search from the nav bar?
  show_search: true
  # Attempt to automatically highlight the active menu link? Can be disabled for complex sites.
  highlight_active_link: true

################
# Localization #
################

date_format: 'Monday, 02 Jan 2006'
time_format: '15:04 MST'
address_format: en-us

#################
# Site features #
#################

highlight: true
highlight_languages:
  - r
  - python
  - latex
math: true
diagram: false
privacy_pack: true
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: true
copyright_license:
  enable: true
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'Licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: 'UA-205605096-1'
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true
